name: widgets
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # LOCAL PACKAGES
  extensions:
    path: ../extensions
  models:
    path: ../models
  
  # IMAGES
  cached_network_image: 3.3.1
  easy_image_viewer: 1.5.0

  # WEB
  url_launcher: 6.3.0
  universal_html: 2.2.4
  # UTILITIES
  oktoast: 3.4.0
  

dev_dependencies:
  lintingpackage:
      path: ../lintingpackage
